'use strict';

export let CanvasAppConstants = {
  INITIALIZE_CANVAS: 'INITIALIZE_CANVAS',
  RESET_CANVAS: 'RESET_CANVAS',
  SELECT_CANVAS_IMAGE: 'SELECT_CANVAS_IMAGE',
  LOAD_IMAGE: 'LOAD_IMAGE',
  SWITCH_CANVAS_MODE: 'SWITCH_CANVAS_MODE',
  CREATE_LABEL_FILE: 'CREATE_LABEL_FILE',
  SAVE_LABEL_FILE: 'SAVE_LABEL_FILE',
  CHANGE_FIGURE_COLOR: 'CHANGE_FIGURE_COLOR',
  COLOR_PICKER_CHANGE: 'COLOR_PICKER_CHANGE',
  SWITCH_ASPECT_FIX_MODE: 'SWITCH_ASPECT_FIX_MODE',
  CHANGE_ASPECT_RATIO: 'CHANGE_ASPECT_RATIO',
  CHANGE_LINE_WIDTH: 'CHANGE_LINE_WIDTH',
  CHANGE_LABEL: 'CHANGE_LABEL',
  TOGGLE_GUIDEWIRE: 'TOGGLE_GUIDEWIRE',
  TOGGLE_GRID: 'TOGGLE_GRID',
  CHANGE_FILE_FORMAT: 'CHANGE_FILE_FORMAT',
  REDO_DRAWING: 'REDO_DRAWING',
  ERASE_ALL: 'ERASE_ALL',
  DELETE_FIGURE: 'DELETE_FIGURE',
  MOVE_IMGLIST_RIGHT: 'MOVE_IMGLIST_RIGHT',
  MOVE_IMGLIST_LEFT: 'MOVE_IMGLIST_LEFT',
  MOUSE_DOWN_ON_CANVAS: 'MOUSE_DOWN_ON_CANVAS',
  MOUSE_MOVE_ON_CANVAS: 'MOUSE_MOVE_ON_CANVAS',
  MOUSE_UP_ON_CANVAS: 'MOUSE_UP_ON_CANVAS'
};
