'use strict';

export var CanvasAppConstants = {
   INITIALIZE_CANVAS: 'INITIALIZE_CANVAS',
   SWITCH_CANVAS_MODE: 'SWITCH_CANVAS_MODE',
   CREATE_LABEL_FILE: 'CREATE_LABEL_FILE',
   SAVE_LABEL_FILE: 'SAVE_LABEL_FILE',
   CHANGE_FIGURE_COLOR: 'CHANGE_FIGURE_COLOR',
   SWITCH_ASPECT_FIX_MODE: 'SWITCH_ASPECT_FIX_MODE',
   CHANGE_ASPECT_RATIO: 'CHANGE_ASPECT_RATIO',
   CHANGE_LINE_WIDTH: 'CHANGE_LINE_WIDTH',
   CHANGE_LABEL: 'CHANGE_LABEL',
   TOGGLE_GUIDEWIRE: 'TOGGLE_GUIDEWIRE',
   TOGGLE_GRID: 'TOGGLE_GRID',
   CHANGE_FILE_FORMAT: 'CHANGE_FILE_FORMAT',
   REDO_DRAWING: 'REDO_DRAWING',
   ERASE_ALL: 'ERASE_ALL'
};
